# 02-HelloTensorflow

In [1]:
# tensorflow 모듈 import
import tensorflow as tf

In [2]:
# constant() 함수를 사용하여 출력할 메시지를 텐서플로우에 입력
hello = tf.constant('안녕, 텐서플로우 !')

# hello 객체는 텐서플로우 자체를 가리키게 된다.
# 텐서가 실행되기 전까지는 tf.constant() 함수로 입력한 문자열이 출력되지 않는다.
# tensorflow는 변수라는 개념이 없다. 그래서 출력하면 아래 출력값처럼 tensorflow 객체가 나온다.
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'\xec\x95\x88\xeb\x85\x95, \xed\x85\x90\xec\x84\x9c\xed\x94\x8c\xeb\xa1\x9c\xec\x9a\xb0 !'>

# 01. tf1 버전의 Hello World

In [3]:
# 세션(텐서플로우 실행기) 객체 생성
# tf1에서 사용하던 기능은 compat.v1 객체 안에 포함되어 있다. -> tf1에서 사용하던 기능을 tf2(현재 사용버전)에서 사용하고 싶을 때 compat.v1을 적으면 된다.
with tf.compat.v1.Session() as sess:
    hello = tf.constant('안녕, 텐서플로우 !')
    
    print(hello)
    
    # 세션 실행
    k = sess.run(hello)
    
    # 실행 결과를 UTF-8로 디코딩 해줘야 한다.
    r = k.decode('utf-8')
    
    # 결과 출력
    print(r)
    
    sess.close()

Tensor("Const:0", shape=(), dtype=string)
안녕, 텐서플로우 !


* 세션을 실행하기 전까지는 그 무엇도 실행되지 않는다. 
* 위의 코드가 2.x버전에서 실행하는 tensorflow 1.x의 코드라고 생각하면 된다. 객체 안에 한국어가 들어있는 경우에는 UTF-8로 디코딩해주어야 문제없이 출력할 수 있다. 

# 02. tf2 버전의 Hello World

* tf1버전과 비교해보면 훨씬 짧은 것을 알 수 있다.

In [4]:
import tensorflow as tf
msg = tf.constant('안녕, 텐서플로우 !')
tf.print(msg)

안녕, 텐서플로우 !


# 03. 텐서의 이해

## 1) 텐서(Tensor) 플로우(Flow)

텐서(Tensor)들을 흘려 보내면서(Flow) 데이터를 처리하는 라이브러리.

## 2) 용어 정리

- 텐서(Tensor) : 다차원배열
- 랭크(Rank) : 텐서의 차원(Dimension). numpy 배열의 shape 값으로 확인 가능

일반적으로 텐서라 함은 Rank가 3인 배열(3차원 배열)

- 스칼라: Rank가 0인 텐서
- 벡터: Rank가 1인 텐서
- 행렬: Rank가 2인 텐서

In [5]:
import numpy as np

In [10]:
# 랭크가 0인 배열 --> 스칼라(값)
a = 100
ts1 = np.array(a)
print(ts1.shape)   # 차원(행,렬)을 보여줌
ts1

()


array(100)

In [8]:
# 랭크가 1인 배열 --> 백터(Vector)
b = [1, 2, 3]
ts2 = np.array(b)
print(ts2.shape)
ts2

(3,)


array([1, 2, 3])

In [9]:
# 랭크가 2인 배열 --> 행렬(Matrix)
c = [ [10,20,30], [100,200,300]]
ts3 = np.array(c)
print(ts3.shape)
ts3

(2, 3)


array([[ 10,  20,  30],
       [100, 200, 300]])

In [11]:
# 랭크가 3인 배열 --> 텐서(Tensor)
d = [ [ [-1, -2, -3], [1, 2, 3] ], [ [-1, 0, 1], [1, 0, -1] ] ]
ts4 = np.array(d)
print(ts4.shape)
ts4

(2, 2, 3)


array([[[-1, -2, -3],
        [ 1,  2,  3]],

       [[-1,  0,  1],
        [ 1,  0, -1]]])

- 텐서플로우의 덧셈뺄셈은 이진구조로 이루어진다....

# 04. 계산 그래프 (Computational Graph)

## 1) 계산 그래프의 의미

컴퓨터 공학에서 정의하는 노드(Node)와 엣지(Edge)로 이루어진 자료구조.

<이미지>

각각의 노드에 연산자나 숫자 등을 넣을 수 있다.
텐서들이 계산 그래프 구조를 통해 노드에서 노드로 이동한다.

텐서플로우 라이브러리는 그래프 구조를 먼저 정의하고 정의한 그래프에 실제 텐서들을 흘려보내도록 디자인되었다.

## 2) 텐서플로우 프로그램의 작성 과정

### 그래프 생성

노드에 연산, 변수, 상수 등을 정의하여 연산 과정을 그래프로 표현한다.

### 그래프 실행

노드간의 연결인 엣지를 통해 텐서를 주고 받으면서 계산을 수행한다.

## 3) 상수 선언하기

```python
node = tf.constant(value, dtype = None, shape = None, name = 'Const')
```

- value : 상수값. 직접 지정하거나 shape 형태(Python의 list 구조)로 채울 ㄱ밧을 지정할 수 있다.
- dtype : 데이터 타입 (ex: tf.float32, tf.int32, tf.bool)
- shape : 상수 데이터의 형태 (배열의 차원)
- name : 텐서의 이름

## 4) 상수 텐서를 정의하고 덧셈 결과 출력하기

### TF2 버전으로 구현하기

In [12]:
# 그래프 노드를 정의하고 출력
# -> 노드의 정보만 출력될 뿐 실제 값이 출력되지는 않는다.
# python에서 보면 hello = 3.0
node1 = tf.constant(3.0, dtype = tf.float32, name = 'hello')
node1

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [13]:
# 암시적으로 타입 지정하기 --> tf.float32 타입으로 선언된다.
# python에서 보면 world = 4.0
node2 = tf.constant(4.0, name = 'world')
node2

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [14]:
# 두 개의 노드의 값을 더하는 연산을 수행하는 node3을 정의
# -> 'node3 = node1 + node2'와 같이 정의해도 같은 결과이다.
# python에서 보면 hello + world
node3 = tf.add(node1, node2)
node3

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [17]:
tf.print(node1)
tf.print(node2)
tf.print(node3)

3
4
7


### TF1 버전으로 구현하기

TF1에서는 항상 session을 생성해주어야 한다.

In [3]:
with tf.compat.v1.Session() as sess:
    node1 = tf.constant(3.0, dtype = tf.float32, name = 'hello')
    node2 = tf.constant(4.0, name = 'world')
    node3 = tf.add(node1, node2)
    print(sess.run(node1))
    print(sess.run(node2))
    print(sess.run(node3))
    
    # 그래프 전체 실행
    print(sess.run([node1, node2, node3]))
    
    sess.close()

3.0
4.0
7.0
[3.0, 4.0, 7.0]


# 05. 텐서보드(Tensorboard)
학습 과정을 기록하고 기록된 결과를 시각화해서 보여주는 도구.
텐서플로우의 계산식을 시각화시켜주는 것

텐서플로우가 생성하는 계산 그래프를 시각화해서 볼 수 있기 때문에 실행 흐름을 이해하는데 도움이 된다.

## 1) 주요 사용 방법

### 요약 정도 생성하기

세션이 실행할 계산 그래프가 저장될 폴더를 지정하여 기록 객체 만들기

```python
writer = tf.summary.FileWriter('폴더경로', 세션객체.graph)
```

In [3]:
import datetime as dt
logdir = 'logs/' + dt.datetime.now().strftime('%y%m%d')
print(logdir)
# logdir에 내가 주피터랩을 오픈한 폴더 속 새로운 폴더명을 입력하여 로그가 저장될 주소를 지정한다.
# 확인해보면 폴더 안에 logs 폴더가 새로 생성되어 있음

with tf.compat.v1.Session() as sess:
    writer = tf.compat.v1.summary.FileWriter(logdir, sess.graph)
    # 여기서부터 모든 로그의 기록이 시작된다. writer를 열어줌.
    
    node1 = tf.constant(3.0, dtype = tf.float32, name = 'hello')
    node2 = tf.constant(4.0, name = 'world')
    node3 = tf.add(node1, node2)
    print(sess.run(node1))
    print(sess.run(node2))
    print(sess.run(node3))
    
    # 그래프 전체 실행
    print(sess.run([node1, node2, node3]))
    
    #기록 종료
    writer.close()

logs/201121
3.0
4.0
7.0
[3.0, 4.0, 7.0]


- 여기서 명령 프롬프트를 하나 더 오픈한다.

```shell
tensorboard --logdir=./logs/201121 --port=9901      # 임의의 숫자 4개
```

마지막에 나오는 주소를 웹브라우저에 실행시킨다. 여기에선 http://localhost:9901/ 가 나온다. 그러면 tensorboard라는 새로운 창이 생성된다.
그럼 그 창에 위에서 실행한 sess의 실행 결과가 노드와 글자로 구성되어 나타난다.

# 06. 변수

Variable()이라는 함수를 사용해서 변수를 만들 수 있다.

## 1) 암묵적 데이터 타입 지정

변수가 생성되는 순간에 데이터의 타입과 크기가 결정된다.


### tf2 버전

In [9]:
x = tf.Variable(123)
x     # x라고만 하면 tensorflow 객체만 출력된다.

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>

In [10]:
tf.print(x)

123


In [5]:
y = tf.Variable(x + 100)
tf.print(y)

223


### tf1 버전

지정된 변수를 초기화하기 위해 `initialize_all_variables()` 라는 함수를 반드시 먼저 호출한다.

In [11]:
with tf.compat.v1.Session() as sess:
    # 변수를 만들기 위한 노드
    x = tf.compat.v1.Variable(123)
    
    # 변수를 초기화하기 위한 노드
    init_op = tf.compat.v1.initialize_all_variables()
    sess.run(init_op)     # 초기화 노드를 먼저 실행
    value = sess.run(x)   # 변수 생성
    print(value)          # 생성된 값 출력

Instructions for updating:
Use `tf.global_variables_initializer` instead.
123


## 2) 명시적 타입 지정

`dtype` 파라미터를 사용한다. 지정된 타입과 다른 형태의 스칼라가 명시될 경우 에러. (가급적 암시적 타입 지정을 사용하는 것이 더 낫다)

> 구글에서 tf.dtypes.DType 으로 검색한 결과 참조 --> tensorflow에서 사용하는 데이터 타입이 정리되어 있다.

In [13]:
x = tf.Variable(123, dtype = tf.int32)
tf.print(x)

123


# 07. 난수

## 1) 균등분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 x가 예상되는 범위 안에서 균등한 확률로 일어날 것이라고 예측될 때 사용한다.

미래 결과값이 경험적으로 알 수 없을 상황에서 사용한다.

### 균등분포 난수의 예 - 주사위에 대한 확률

- 200번을 던지고 201번째 주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지의 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며, 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.

> tf1에서는 `tf.random_uniform()` 함수 사용. 파라미터는 동일

In [14]:
# 스칼라 형태의 균등분포 난수
rnd1 = tf.random.uniform(shape = [], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(rnd1)

53


In [18]:
# 벡터 형태의 균등분포 난수
# 생성되는 리스트의 원소는 각각 연관이 없다.
rnd2 = tf.random.uniform(shape = [5], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(rnd2)

[9 67 59 47 74]


In [20]:
# 행렬 형태의 균등분포 난수
rnd2 = tf.random.uniform(shape = [2,3], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(rnd2)

[[46 62 41]
 [31 22 95]]


In [36]:
# 텐서 형태의 균등분포 난수: tensor는 3차원 형태의 값
rnd2 = tf.random.uniform(shape = [2,3,4], minval = 0, maxval = 100, dtype = tf.int32)
tf.print(rnd2)

[[[89 90 76 54]
  [4 67 21 66]
  [10 58 95 84]]

 [[85 87 67 41]
  [2 39 8 38]
  [42 28 69 81]]]


## 2) 정규분포 난수

과거의 축적된 경험적 데이터를 이미 보유하고 있어 이를 이용하여 미래에 발생할 결과값 x의 각 예상되는 벌위별로 발생될 확률을 어느정도 추정할 수 있을 때 사용

텐서에서는 과거의 경험에 대한 평균과 표준편차를 '직접' 지정하여 그에대한 정규분포값을 산정한다.

### 정규분포 난수의 예 - 매장의 매출액 예측

- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백만원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- 평균에 대한 예측 : 이번 달 매출은 과거 3개월의 매출 평균인 2천백만원으로 예측.
- 범위에 대한 예측 : 최소 2천만원 ~ 최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

### 참고

- 편차(deviation) : 관측값에서 평균 또는 중앙값을 뺀 값
- 분산(variance) : 관측값에서 평균을 뺀 값을 제곱하고, 그것을 모두 더한 후 전체 개수로 나눈 값(=차이값의 제곱의 평균). 관측값에서 평균을 뺀 값인 편차를 모두 더하면 0이 나오므로 제곱해서 더한다.
- 표준편차(standard deviation) : 분산의 제곱근. 제곱해서 값이 부풀려진 분산을 제곱근해서 다시 원래 크기로 만들어준 상태.

In [23]:
# 스칼라 형태의 정규분포 난수 -> 평균과 표준편차를 지정해준다.
normal_rnd1 = tf.random.normal(shape = [], mean = 0.0, stddev = 1.0)
tf.print(normal_rnd1)

-0.982854903


In [25]:
# 벡터 형태의 정규분포 난수
normal_rnd2 = tf.random.normal(shape = [5], mean = 0.0, stddev = 1.0)
tf.print(uni_rnd2)

[0.511626959 -0.445747048 0.714480519 -0.713507175 1.31704235]


In [28]:
# 행렬 형태의 정규분포 난수
normal_rnd3 = tf.random.normal(shape = [2,3], mean = 0.0, stddev = 1.0)
tf.print(normal_rnd3)

[[1.12223744 -0.468763322 0.565362096]
 [-1.86115932 -1.06715977 1.93411148]]


## 3) 랜덤값을 갖는 행렬곱 예시

In [37]:
# 랜덤값을 갖는 3행 2열의 행렬을 변수 x로 정의
# random.uniform의 파라미터 기본값? minval = 0, maxval = 1, dtype = tf.float32
x = tf.Variable(tf.random.uniform([3,2]))

# 랜덤값을 갖는 2행 1열의 행렬을 변수 y로 정의
y = tf.Variable(tf.random.uniform([2,1]))

# 행렬곱에 대한 연산을 수행하는 노드 정의
expr = tf.matmul(x,y)   # matrix multiply
tf.print(expr)
# 여기선 [3,2] * [2,1]이므로 결과값은 [3,1] 즉 3행 1열이 된다.

[[0.80239141]
 [0.431075126]
 [0.271013856]]
